openapi: 3.0.0
info:
  title: mmfsl-dfb-apigee-proxies Copy 2
  description: please add your description
  version: 1.0.0

servers:
  - url: https://{{hostname}}

paths:
  /bre/MOBILE:
    post:
      summary: MOBILE
      parameters:
             - in: header
               name: Content-Type
               required: true
               schema:
                 type: string
               example:
                 application/json
             - in: header
               name: channelID
               required: true
               schema:
                 type: string
               example:
                 Sodel
             - in: header
               name: serviceName
               required: true
               schema:
                 type: string
               example:
                 MOBILE
             - in: header
               name: uniqueRefNo
               required: true
               schema:
                 type: string
               example:
                 12341234
             - in: header
               name: timestamp
               required: true
               schema:
                 type: string
               example:
                 {{$isoTimestamp}}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                MOBILE:
                  type: string
                DPD:
                  type: number
            example: {

    "MOBILE": "6417910989",

    "DPD": 1

}
      responses:
        "200":
          description: it is an example response
          content:
            JSON/application:
              schema:
                type: object
              example:
                {}
  /bre/PAN:
    post:
      summary: PAN
      parameters:
             - in: header
               name: Content-Type
               required: true
               schema:
                 type: string
               example:
                 application/json
             - in: header
               name: channelID
               required: true
               schema:
                 type: string
               example:
                 Sodel
             - in: header
               name: serviceName
               required: true
               schema:
                 type: string
               example:
                 PAN
             - in: header
               name: uniqueRefNo
               required: true
               schema:
                 type: string
               example:
                 12341234
             - in: header
               name: timestamp
               required: true
               schema:
                 type: string
               example:
                 {{$isoTimestamp}}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                PAN:
                  type: string
                DPD:
                  type: number
            example: {

    "PAN": "CNDPM3853K",

    "DPD": 23

}
      responses:
        "200":
          description: it is an example response
          content:
            JSON/application:
              schema:
                type: object
              example:
                {}